### ISSUE TITLE
Compatibility with specific CitySports treadmill

### ISSUE THREAD

**Issue by sander1095** [hughesjs/FitnessMachine#62]
Is this project capable of controlling this treadmill without the remote? 

 https://amzn.eu/d/8R1CuXS

If not, what models are supported?

**Comment by hughesjs** [comment]
Hi mate, it's hard to know as their ads aren't really great at saying what is an isn't supported. I *think* this app should work with any of their treadmills that support their app. I don't see why they'd use a different protocol for different treadmills when they're broadly following the BLE Fitness Machine standard.

This is the one I have though if you want to be sure: https://www.amazon.co.uk/gp/product/B0BX5KTLCL/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

Please note though that the app is still heavily under development (when I have time). I haven't published it on any app stores yet for that reason. I also don't have an Android device to test it on. If you do find that the model of treadmill you end up with doesn't work, or have issues with the Android build, I'd be happy to work with you on fixing them though.

**Comment by sander1095** [comment]
Thanks for the swift reply! 😁

The one I linked only has a remote, it seems. 

I guess that uses IR, not bluetooth. Someone I know has that treadmill I linked and said the Eqisports app does not work on that model, so your app wouldn't be able to function(, right?)

I have an android phone and am considering buying a treadmill. However, I would only buy one that has a desktop app available because we all have enough remotes in our lives ;). I'd love to use a keyboard shortcut to tweak it to reduce distractions during the day.

Because your app is using MAUI (🤟) I guess it should also be able to run/could be made runnable on Windows.

**Comment by hughesjs** [comment]
So mine also has a remote but yeah, it relies on BLE for the app. So if it's an IR only model, it won't work.

So the proof of concept was in MAUI, I've pivotted to using Flutter for the full app because I was struggling with the lack of decent component libraries for MAUI. The same is true though, but I haven't, at this time, checked to see if FlutterBlue (the BLE lib I'm using) works with Windows.

Happy to have you on board if you wanted to chip in though.

**Comment by hughesjs** [comment]
A quick look would indicate that it's doable: https://pub.dev/packages/flutter_blue_plus_windows

I'm probably about to rewrite a few bits of the app over the next few weeks to account for the things I've learned since diving in head-first with a language and a framework I didn't know. So might be a good time to add this in.

**Comment by hughesjs** [comment]
I'm going to close this, but feel free to reopen it if you get a treadmill and want to report on whether it works or not :)
